FROM centos:7.3.1611

MAINTAINER zhoub

RUN yum update -y 
RUN yum install -y epel-release openssh openssh-clients openssh-server
RUN yum update -y

RUN curl --silent --location https://rpm.nodesource.com/setup_6.x | bash -
RUN yum install -y nodejs
RUN yum clean all

EXPOSE 5000
EXPOSE 22
